// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wfm.Forecasting.Infrastructure.Persistence;

#nullable disable

namespace Wfm.Forecasting.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WfmDbContext))]
    [Migration("20260623140605_AddSkillOperatingHours")]
    partial class AddSkillOperatingHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wfm.Forecasting.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("operating_hours");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.ForecastJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("Status");

                    b.ToTable("forecast_jobs", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("queues", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.QueueIntervalStat", b =>
                {
                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<DateTimeOffset>("IntervalStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interval_start");

                    b.Property<int>("AhtSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("aht_seconds");

                    b.Property<int>("Contacts")
                        .HasColumnType("integer")
                        .HasColumnName("contacts");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("QueueId", "IntervalStart");

                    b.HasIndex("TenantId");

                    b.ToTable("queue_interval_stats", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.SkillForecast", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<DateTimeOffset>("IntervalStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interval_start");

                    b.Property<int>("AhtSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("aht_seconds");

                    b.Property<int>("Contacts")
                        .HasColumnType("integer")
                        .HasColumnName("contacts");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("SkillId", "IntervalStart");

                    b.HasIndex("TenantId");

                    b.ToTable("skill_forecasts", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.SkillIntervalStat", b =>
                {
                    b.Property<int>("AhtSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("aht_seconds");

                    b.Property<int>("Contacts")
                        .HasColumnType("integer")
                        .HasColumnName("contacts");

                    b.Property<DateTimeOffset>("IntervalStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interval_start");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.ToTable((string)null);

                    b.ToView("skill_interval_stats", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.SkillQueue", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("SkillId", "QueueId");

                    b.HasIndex("QueueId");

                    b.HasIndex("TenantId");

                    b.ToTable("skill_queues", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Wfm.Forecasting.Domain.Skill", b =>
                {
                    b.HasOne("Wfm.Forecasting.Infrastructure.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.ForecastJob", b =>
                {
                    b.HasOne("Wfm.Forecasting.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.Queue", b =>
                {
                    b.HasOne("Wfm.Forecasting.Infrastructure.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.QueueIntervalStat", b =>
                {
                    b.HasOne("Wfm.Forecasting.Infrastructure.Persistence.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.SkillForecast", b =>
                {
                    b.HasOne("Wfm.Forecasting.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfm.Forecasting.Infrastructure.Persistence.SkillQueue", b =>
                {
                    b.HasOne("Wfm.Forecasting.Infrastructure.Persistence.Queue", null)
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfm.Forecasting.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
